file-version: 1
# UUID's of the Player that should have admins perms.
admins: 74401e14-f69c-48f3-b393-64be488dff8f,069a79f4-44e9-4726-a5be-fca90e38aaf5
# Velocity Secret
vsecret: <VELOCITY-SECRET>
# Docherhub Template for the Default-Servers.
default-template: anton691/simple-lobby:latest
# 5 is the player limit for the default servers, and 3 is the threshold for creating a new server.
default-new-create-count: 3/5
# Hold-Servers, at least one.
manager-servers:
  server-1:
    ip: localhost
    username: notrootpls
    password: 1234
# Gamemodes which players can join.
gamemodes:
  Duels:
    templateName: anton691/simple-duels:latest
    neededPlayers: 2

