file-version: 1
default-server: lobby
admins: 74401e14-f69c-48f3-b393-64be488dff8f,069a79f4-44e9-4726-a5be-fca90e38aaf5

manager-servers:
  server-1:
    ip: localhost
    port: 5000
    password: 1234


